---
### geoschem_config.yml: GEOS-Chem Runtime configuration options.
### Customized for GCHP simulations using the KPP "fullchem" mechanism.
###
### NOTE: Add quotes around nitrogen oxide ('NO'), because YAML
### parsers will confuse this with a negative "no" value.

#============================================================================
# Simulation settings
#============================================================================
simulation:
  name: Hg
  chem_inputs_dir: ./ChemDir/
  species_database_file: ./species_database.yml
  species_metadata_output_file: OutputDir/geoschem_species_metadata.yml
  debug_printout: true

#============================================================================
# Timesteps settings
#
# These timesteps are determined in setCommonRunSettings.sh since they are
# resolution-dependent for GCHP
#============================================================================
timesteps:
  transport_timestep_in_s: 600
  chemistry_timestep_in_s: 1200
  radiation_timestep_in_s: 10800

#============================================================================
# Settings for GEOS-Chem operations
#============================================================================
operations:

  chemistry:
    activate: true

  convection:
    activate: true

  dry_deposition:
    activate: true
    diag_alt_above_sfc_in_m: 10

  pbl_mixing:
     activate: true
     use_non_local_pbl: true

  photolysis:
    input_dir: /net/geoschem/data/gcgrid/data/ExtData//CHEM_INPUTS/FAST_JX/v2022-08-Hg/
    overhead_O3:
      use_online_O3_from_model: true
      use_column_O3_from_met: true
      use_TOMS_SBUV_O3: false

  transport:
    activate: true
    transported_species:
      -  Hg0
      -  HgBr
      -  HgBrNO2
      -  HgBrHO2
      -  HgBrBrO
      -  HgBrClO
      -  HgBrOH
      -  HgBr2
      -  HgCl
      -  HgClNO2
      -  HgClHO2
      -  HgClClO
      -  HgClBrO
      -  HgClBr
      -  HgClOH
      -  HgOH
      -  HgOHNO2
      -  HgOHHO2
      -  HgOHClO
      -  HgOHBrO
      -  HgOHOH
      -  HgCl2
      -  Hg2ClP
      -  Hg2ORGP
      -  Hg2STRP

  wet_deposition:
    activate: true

#============================================================================
# Settings for GEOS-Chem aerosols
#============================================================================
Hg_simulation_options:

  sources:
    use_dynamic_ocean_Hg: false
    use_preindustrial_Hg: false
    use_arctic_river_Hg: true

  chemistry:
    tie_HgIIaq_reduction_to_UVB: false

  # NOTE: GTMM is currently, we look to the Hg & POPs community
  # to take the lead in restoring it. (bmy, 04 Apr 2022)
  GTMM_soil_model:
    activate: false
    restart_file: N/A

#============================================================================
# Settings for diagnostics (other than HISTORY and HEMCO)
#============================================================================
extra_diagnostics:

  obspack:
    activate: false
    quiet_logfile_output: false
    input_file: ./obspack_co2_1_OCO2MIP_2018-11-28.YYYYMMDD.nc
    output_file: ./OutputDir/GEOSChem.ObsPack.YYYYMMDD_hhmmz.nc4
    output_species:
      - Hg0

  planeflight:
    activate: false
    flight_track_file: Planeflight.dat.YYYYMMDD
    output_file: plane.log.YYYYMMDD
    
